#!/usr/bin/env Rscript
root <- pkgload::pkg_path()
if (pkgload::pkg_name(root) != "outpack.server") {
  stop("Expected this script to be run from within outpack.server")
}
copy <- c("metadata.json", "id.json", "hash.json")
src <- system.file(file.path("schema", copy), package = "outpack")
fs::file_copy(src, file.path(root, "inst", "schema"), overwrite = TRUE)
