# Generated by porcelain: do not edit by hand
`__porcelain__` <- function() {
  list(
    "GET /" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/",
        root,
        returning = porcelain::porcelain_returning_json("root"),
        validate = validate)
    },
    "GET /metadata/list" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/metadata/list",
        metadata_list,
        porcelain::porcelain_state(root = state$root),
        returning = porcelain::porcelain_returning_json("list"),
        validate = validate)
    },
    "GET /metadata/<id>/json" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/metadata/<id>/json",
        metadata_get_json,
        porcelain::porcelain_state(root = state$root),
        returning = porcelain::porcelain_returning_json("metadata"),
        validate = validate)
    },
    "GET /metadata/<id>/text" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/metadata/<id>/text",
        metadata_get_text,
        porcelain::porcelain_state(root = state$root),
        returning = porcelain::porcelain_returning_text(),
        validate = validate)
    },
    "GET /file/<hash>" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/file/<hash>",
        file_get,
        porcelain::porcelain_state(root = state$root),
        returning = porcelain::porcelain_returning_binary(),
        validate = validate)
    })
}
